apiVersion: apps/v1
kind: Deployment
metadata:
  name: ismaila-mendy-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ismaila-mendy-app
  template:
    metadata:
      labels:
        app: ismaila-mendy-app
    spec:
      containers:
        - name: ismaila-mendy-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
