apiVersion: v1
kind: Service
metadata:
  name: ismaila-mendy-app
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ismaila-mendy-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
