image:
  repository: ghcr.io/lorem0221/ismaila-mendy-app
  tag: "d624a652c169743df6b5582dc9979e0d622ff72d"
  pullPolicy: IfNotPresent

namespace: ismaila-mendy-ns

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 5000
