image:
  repository: ghcr.io/lorem0221/ismaila-mendy-app
  tag: "2d2d73acee643622a9b46758d5b49cd9d736dd30"
  pullPolicy: IfNotPresent

namespace: ismaila-mendy-ns

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 5000
